networks:
  demo_api:
    driver: bridge

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 4040:8080
    networks:
      - demo_api

  postgres:
    image: "postgres:15"
    container_name: postgres_demo
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 15432:5432

    networks:
      - demo_api

  api:
    cap_add:
      - SYS_PTRACE
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_demo
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 5312:5312
      - 5678:5678
    command: >
      bash -c "
      pip install -e ".[dev]" && \
      cd alembic && alembic upgrade head && \ 
      cd /app && \
      uvicorn app.main:app --host 0.0.0.0 --port 5312 --reload --log-config logging.ini
      "
    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - demo_api

